config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'cooking_details/new'
    get 'cooking_details/create'
    get 'cooking_details/edit'
    get 'cooking_details/update'
    get 'cooking_details/destroy'
  end
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  devise_for :members,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
   scope module: :public do
    root to: "homes#top"
    get "home/about" => "homes#about", as: "about"
    
    resources :cookings do
      resources :cooking_details, only: [:new, :create, :edit, :update, :destroy]
      resources :bookmarks, only: [:index, :destroy, :create]
      resources :cooking_comments, only: [:index, :destroy, :create]
    end
    get 'search' => 'cookings#search'
    resources :members, only: [:show, :edit, :update]
    get "member/quit" => "members#quit"
    patch "member/out" => "members#out"
    
    
    
  end
  
  namespace :admin do
    #root to: "homes#top"
    resources :cookings, only: [:index, :show, :edit, :update, :destroy] do
      resources :cooking_comments, only: [:index, :destroy]
    end
    resources :tags, only: [:create, :index, :edit, :update, :destroy]
    resources :members, only: [:show, :index, :edit, :update]
    
    
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  
  has_many :cookings
  #has_many :tagmaps, dependent: :destroy
  
  #validates :name, presence: true
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  
  def index
    @tag = Tag.new
    @tags = Tag.all
  end
  
  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path
    else
      redirect_to admin_tags_path
    end
  end
  
  def edit
    @tag = Tag.find(params[:id])
  end
  
  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path
    else
      redirect_to edit_admin_tag_path(@tag)
    end
  end
  
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to admin_tags_path
  end
  
  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/edit.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-md-5 offset-md-1">
      <h4><span class="pr-4 pl-4" style="background-color:whitesmoke;">タグ編集</span></h4>
    </div>
  </div>
  <% if @tag.errors.any? %>
  <%= @tag.errors.count %>件のエラーが発生しました
    <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row mt-5">
    <div class="col-md-6">

<%= form_with model: @tag,url: admin_tag_path do |f| %>
<table class="table">
  <tr>
    <td><%= f.label :name, "ジャンル名"%></td>
    <td><%= f.text_field :name %></td>
    <td><%= f.submit '変更を保存', class:"btn btn-md btn-success", style: "border-radius: 10px;" %></td>
  </tr>
</table>
<% end %>

app/views/admin/tags/index.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-md-5 offset-md-1">
      <h4><span class="pr-4 pl-4" style="background-color:whitesmoke;">タグ追加</span></h4>
    </div>
  </div>
  <% if @tag.errors.any? %>
  <%= @tag.errors.count %>件のエラーが発生しました
    <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row mt-5">
    <div class="col-md-6">
      <%= form_with model: @tag,url: admin_tags_path do |f| %>
      <table class="table">
        <tr>
          <td><%= f.label :name, "タグ名"%></td>
          <td><%= f.text_field :name %></td>
          <td><%= f.submit '新規登録', class:"btn btn-md btn-success", style: "border-radius: 10px;" %></td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
  <div class="row md-5">
    <div class="col-lg-4">
        <table class="table">  
          <tr style="background-color:whitesmoke;">
            <td class="text-center">タグ一覧</td>
            <td></td>
          </tr>
        </table>
        <% @tags.each do |tag| %>
        <table class="table">
          <tr>
            <td>
              <%= tag.name %> 
            </td>
            <td class="text-right">
              <%= link_to  "編集する", edit_admin_tag_path(tag), class:"btn btn-sm btn-success", style: "border-radius: 10px;" %>
              <%#= link_to "削除", admin_tag_path(tag), method: :delete, class:"btn btn-sm btn-danger", style: "border-radius: 10px;" %>
            </td>
          </tr>
        </table>
        <% end %>
    </div>
  </div>
</div>