config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'cooking_details/new'
    get 'cooking_details/create'
    get 'cooking_details/edit'
    get 'cooking_details/update'
    get 'cooking_details/destroy'
  end
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  devise_for :members,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
   scope module: :public do
    root to: "homes#top"
    get "home/about" => "homes#about", as: "about"
    
    resources :cookings do
      resources :cooking_details, only: [:new, :create, :edit, :update, :destroy]
      resources :bookmarks, only: [:index, :destroy, :create]
      resources :cooking_comments, only: [:index, :destroy, :create]
    end
    get 'search' => 'cookings#search'
    resources :members, only: [:show, :edit, :update]
    get "member/quit" => "members#quit"
    patch "member/out" => "members#out"
    
    
    
  end
  
  namespace :admin do
    #root to: "homes#top"
    resources :cookings, only: [:index, :show, :edit, :update, :destroy] do
      resources :cooking_comments, only: [:index, :destroy]
    end
    resources :tags, only: [:create, :index, :edit, :update, :destroy]
    resources :members, only: [:show, :index, :edit, :update]
    
    
  end
end

app/models/cooking.rb
class Cooking < ApplicationRecord
  
  has_one_attached :image
  #has_many_attached :images
  
  has_many :cooking_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :cooking_details
  belongs_to :member
#   has_many :tagmaps, dependent: :destroy
  belongs_to :tag#, through: :tagmaps
  
  
  
  #validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  
  def self.search(keyword)
    where(["name like?", "%#{keyword}%"])
  end
  
  def bookmarked_by?(member)
    bookmarks.where(member_id: member).exists?
  end
  
  #def save_cookings(tags)
  # current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
  # old_tags = current_tags - tags
  # new_tags = tags - current_tags

   # Destroy
  # old_tags.each do |old_name|
  #   self.tags.delete Tag.find_by(tag_name:old_name)
  # end

    #Create
  # new_tags.each do |new_name|
  #   cooking_tag = Tag.find_or_create_by(tag_name:new_name)
  #   self.tags << cooking_tag
 #  end
  #end
end

app/controllers/admin/cookings_controller.rb
class Admin::CookingsController < ApplicationController
  
  def index
    @cookings = Cooking.page(params[:page]).per(15)
    #@cookings = current_member.cookings.all
    #@cooking = current_member.cookings.new
  end
  
  def show
    @cooking = Cooking.find(params[:id])
    @cooking_comments = @cooking.cooking_comments.order(created_at: :desc)
    #@cooking_comment = current_member.cooking_comments.new
  end
  
  def edit
    @cooking = Cooking.find(params[:id])
    @tags = Tag.all
  end
  
  def update
    @cooking = Cooking.find(params[:id])
    if @cooking.update(cooking_params)
      redirect_to admin_cookings_path
    else
      redirect_to edit_admin_cooking_path(cooking_id)
    end
  end
  
  def destroy
    @cooking = Cooking.find(params[:id])
    @cooking.destroy
    redirect_to admin_cookings_path
  end
  
  private
  def cooking_params
    params.require(:cooking).permit(:comment, :name, :image, :introduction, :tag_id, :member_id)
  end
end

app/helpers/admin/cookings_helper.rb
module Admin::CookingsHelper
end

app/views/admin/cookings/edit.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-md-3 offset-md-1">
      <h4><span class="pr-4 pl-4" style="background-color:whitesmoke;">料理編集フォーム</span></h4>
    </div>
  </div>
  <% if @cooking.errors.any? %>
  <%= @cooking.errors.count %>件のエラーが発生しました
    <ul>
      <% @cooking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
 <div class="row mt-5">
    <div class="col-md-7 offset-md-2">
    
            <%= form_with model: @cooking,url: admin_cooking_path do |f| %>
            <table class="table">
              <tr>
                <td><%= f.label :image, "料理画像"%></td>
                <td><%= f.file_field :image, accept: "image/*" %></td>
              </tr>
              <tr>
                <td><%= f.label :name, "料理名"%></td>
                <td><%= f.text_field :name, class: "form-control", style: "width:400px;" %></td>
              </tr>
              
              <tr>
                <td><%= f.label :tag, "タグ設定"%></td>
                <td><%= f.collection_select(:tag_id, @tags, :id, :name)  %></td>
              </tr>
              <tr>
                <td><%= f.label :introduction, "概要欄"%></td>
                <td><%= f.text_area :introduction, placeholder: "一言や材料などを書き込んで下さい。", style: "width:400px;" %></td>
              </tr>
             
              <tr>
                <td></td>
                <td class="text-center"><%= f.submit '投稿する', class:"btn btn-lg btn-success", style: "border-radius: 10px;" %></td>
              </tr>
            </table>
            <% end %>
            
      </div>
    </div>
  </div>
</div>

app/views/admin/cookings/index.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-md-9 offset-md-1">
      <h4><span class="pr-4 pl-4" style="background-color:whitesmoke;">料理一覧</span></h4>
    </div>
  </div>
  
  <div class="row mt-5">
    <div class="col-lg-12">
      
<table class="table table-bordered">
  <thead>
    <tr>
      <th>料理ID</th>
      <th>料理名</th>
      <th>投稿者</th>
      <th>タグ名</th>
    </tr>
  </thead>
  <% @cookings.each do |cooking| %>
  <tbody>
    <tr>
      <td><%= cooking.id %></td>
      <td><%= link_to admin_cooking_path(cooking.id) do %>
               <%= cooking.name %>
          <% end %></td>
     
      <td><%= cooking.member.name %></td>
      <td><%= cooking.tag.name %></td>
    </tr>
  </tbody>
  <% end %>
</table>

    </div>
  </div>
  <div class="row mt-5">
    <div class="col-lg-6 offset-md-5">
      <div class="text-center"><%= paginate @cookings %></div>
    </div>
  </div>
</div>

app/views/admin/cookings/show.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-md-8 offset-md-1">
      <h4><span class="pr-4 pl-4" style="background-color:whitesmoke;"><%= @cooking.name %></span></h4>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-3">
       <% if @cooking.image.attached? %>
        <%= image_tag @cooking.image, :size =>'300x300' %>
      <% else %>
        <%= image_tag asset_path("default-image.jpg"), :size =>'300x300' %></br>
      <% end %>
    </div>
    <div class="col-6 offset-1">
      <table class="table">
        <tbody>
          <tr>
            <td><%= @cooking.name %></td>
          </tr>
          <tr>
            <td><%= @cooking.member.name %></td>
          </tr>
          <tr>
            <td><%= @cooking.tag.name %></td>
          </tr>
          <tr>
            <td><%= @cooking.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
        <tbody>
      </table>
    </div>
    <div class="col-2">
      <div style="flex-direction:column;">
        <%= link_to "編集", edit_admin_cooking_path(@cooking), class:"btn btn-lg btn-success", style: "border-radius: 10px;" %>
        <%= link_to "削除", admin_cooking_path(@cooking), data: {confirm: '本当に削除しますか？'}, method: :delete, class:"btn btn-lg btn-danger", style: "border-radius: 10px;" %>
      </div> 
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-lg-8">
      <div class="border" style="padding:10px;">
        <%= @cooking.introduction %>
      </div>
    </div>
  </div>
  <div class="row mt-5 mb-5">
    <div class="col-10">
      
      <p>コメント件数：<%= @cooking.cooking_comments.count %></p>
      <% @cooking_comments.each do |comment| %>
       <div style="display:flex;">
        <%= image_tag comment.member.get_profile_image(50,50) %>
        <h6 style="line-height:50px;">投稿者:<%= comment.member.name %></h6>
        <div style="padding-left:50px; line-height:50px;">
          <%= simple_format(comment.comment) %>
        </div> 
       </div> 
          
          <%= link_to '削除', admin_cooking_cooking_comment_path(@cooking, comment), data: {confirm: '本当に削除しますか？'}, method: :delete %>
        
      <% end %>
    </div>
    
  </div>
</div>