config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'cooking_details/new'
    get 'cooking_details/create'
    get 'cooking_details/edit'
    get 'cooking_details/update'
    get 'cooking_details/destroy'
  end
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  devise_for :members,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
   scope module: :public do
    root to: "homes#top"
    get "home/about" => "homes#about", as: "about"
    
    resources :cookings do
      resources :cooking_details, only: [:new, :create, :edit, :update, :destroy]
      resources :bookmarks, only: [:index, :destroy, :create]
      resources :cooking_comments, only: [:index, :destroy, :create]
    end
    get 'search' => 'cookings#search'
    resources :members, only: [:show, :edit, :update]
    get "member/quit" => "members#quit"
    patch "member/out" => "members#out"
    
    
    
  end
  
  namespace :admin do
    #root to: "homes#top"
    resources :cookings, only: [:index, :show, :edit, :update, :destroy] do
      resources :cooking_comments, only: [:index, :destroy]
    end
    resources :tags, only: [:create, :index, :edit, :update, :destroy]
    resources :members, only: [:show, :index, :edit, :update]
    
    
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ねばねば料理</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-success">
         <div class="container">
           <a class="navbar-brand" href="/">
             <span>ねばねば料理</span>
           </a>
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
           </button>
           <div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
             <ul class="navbar-nav ml-auto">
              <% if member_signed_in? %>
               <li class="nav-item">
                 <%= link_to "マイページ", member_path(current_member.id), class: 'nav-link text-light' %>
               </li>
               <li class="nav-item">
                 <%= link_to "料理一覧", cookings_path, class: 'nav-link text-light' %>
               </li>
               
               <li class="nav-item">
                  <%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: 'nav-link text-light' %>
               </li>
              <% elsif admin_signed_in? %>
                <li class="nav-item">
                 <%= link_to "料理一覧", admin_cookings_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                 <%= link_to "会員一覧", admin_members_path, class: 'nav-link text-light' %>
                </li>
                
                <li class="nav-item">
                 <%= link_to "タグ一覧", admin_tags_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
                </li>
              <% else %>
              <li class="nav-item">
                 <%= link_to "新規登録", new_member_registration_path, class: 'nav-link text-light' %>
               </li>
               <li class="nav-item">
                 <%= link_to "About", "/home/about", class: 'nav-link text-light' %>
               </li>
               <li class="nav-item">
                 <%= link_to "料理一覧", cookings_path, class: 'nav-link text-light' %>
               </li>
               
               <li class="nav-item">
                <%= link_to "ログイン", new_member_session_path, class: 'nav-link text-light' %>
               </li>
              <% end %>
              
              
           </div>
         </div>
      </nav> 
        
    
  </header>
  <main class="mb-auto">
    <%= yield %>
  </main>
  <footer class="bg-success text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>ねばねば食材が大好きな人達のコミュニティ</p>
            
          </div>
          <!--<div class="col-md-8">-->
          <!--  <h6 class="text-white mt-2 mb-3">Link</h6>-->
          <!--  <ul class="p-0 list-unstyled">-->
          <!--    <li>-->
          <!--      <a href="" title="About" class="text-white-50">会社概要</a>-->
          <!--    </li>-->
          <!--    <li>-->
          <!--      <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>-->
          <!--    </li>-->
          <!--  </ul>-->
          <!--</div>-->
        </div>
      </div>
    </footer>
  </body>
</html>